CREATE OR REPLACE PROCEDURE "AD_STP_AD_TGFCTC" AS
    BEGIN
    INSERT INTO AD_TGFCTC (NUNOTA,NUMNOTA,CODPARC,CODVEND,VLRNOTA,CODTIPOPER,CODTIPVENDA,DTNEG,DTFATUR)
    SELECT
        NUNOTA,
        NUMNOTA,
        CODPARC,
        CODVEND,
        VLRNOTA,
        CODTIPOPER,
        CODTIPVENDA,
        TO_CHAR(DTNEG,'DD/MM/YYYY') AS DTNEG,
        DTFATUR
    FROM TGFCAB
    WHERE
        STATUSNOTA = 'L' AND
        STATUSNFE = 'A' AND
        TIPMOV IN ('V','D','E') AND
        (CODTIPOPER IN (
            SELECT CODTIPOPER FROM TGFTOP WHERE GRUPO = 'Vendas' AND ATUALEST = 'B' AND CODMODDOC = 55    
        ) OR CODTIPOPER IN (1200,1201,1209,300,301,1720,1729)) AND
        DTNEG = TO_CHAR(SYSDATE,'DD/MM/YYYY');
END;