SELECT 
    EXC.CODPROD,
    PRO.DESCRPROD,
    EXC.VLRVENDA,
    (EXC.VLRVENDA + (EXC.VLRVENDA * 3 / 100)) AS VLR_ATUALIZADO
FROM TGFEXC EXC
    INNER JOIN TGFPRO PRO ON PRO.CODPROD = EXC.CODPROD
WHERE 
    PRO.CODGRUPOPROD = 34013 AND
    EXC.NUTAB IN (
        SELECT NUTAB FROM TGFTAB WHERE CODTAB = 0)


UPDATE TGFEXC SET VLRVENDA = (VLRVENDA + (VLRVENDA * 3 / 100))
WHERE NUTAB IN (SELECT NUTAB FROM TGFTAB WHERE CODTAB = 0) AND
    CODPROD IN (
        SELECT CODPROD
        FROM TGFPRO WHERE 
            CODPROD IN (26038,26760,36385,36386,36751,36752,32746,32747)
    )