WITH TAB_EMAILS AS (
    SELECT
        CODPARC,
        EMAILNFE
    FROM TGFPAR WHERE CLIENTE = 'S' AND EMAILNFE IS NOT NULL AND CODPARC >= 5000 AND CODPARC <= 9999
)SELECT
    CODPARC,
    REGEXP_SUBSTR(EMAILNFE,'[^;]+',1,LEVEL) AS EMAILS
FROM TAB_EMAILS 
    CONNECT BY REGEXP_SUBSTR(EMAILNFE,'[^;]+',1,LEVEL) IS NOT NULL