WITH TAB_P2 AS (
    SELECT
        EXC.CODPROD AS CODPROD,
        EXC.VLRVENDA AS VLRVENDA,
        ITE.IDALIQICMS,
        NVL((
        	SELECT DISTINCT ((SELECT SUM(EST.ESTOQUE) FROM TGFEST EST WHERE  ITE.CODPROD=EST.CODPROD
                AND ITE.CONTROLE=EST.CONTROLE
                AND ITE.CODLOCALORIG=EST.CODLOCAL )-(SELECT SUM(E.RESERVADO) FROM TGFEST E WHERE  ITE.CODPROD=E.CODPROD
                AND ITE.CONTROLE=E.CONTROLE
                AND ITE.CODLOCALORIG=E.CODLOCAL))
                FROM TGFEST
                WHERE ITE.CODPROD=TGFEST.CODPROD
                    AND ITE.CONTROLE=TGFEST.CONTROLE
                    AND ITE.CODLOCALORIG=TGFEST.CODLOCAL
    	), 0) as DISPONIVEL
    FROM TGFEXC EXC
        LEFT JOIN TGFITE ITE ON ITE.CODPROD = EXC.CODPROD
    WHERE 
        EXC.NUTAB = (SELECT MAX(NUTAB) FROM TGFTAB WHERE CODTAB = 2) AND
        ITE.NUNOTA = 188538
)
SELECT
    GRU.AD_SEQAPRESENT AS SEQUENCIA,
    P2.CODPROD,
    PRO.DESCRPROD,
    PRO.MARCA,
    GRU.DESCRGRUPOPROD,
    PRO.REFFORN,
    PRO.NCM,
    PRO.IMAGEM,
    PRO.CODVOL,
    P2.VLRVENDA AS VLRUNIT,
    PR.VLRVENDA,
    (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN P2.VLRVENDA ELSE 0 END) AS BASEIPI,
    (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN NVL(I.PERCENTUAL,0) ELSE 0 END) AS ALIQIPI,
    (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END) AS VLRIPI,
    (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN ((P2.VLRVENDA + (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100)) ELSE 0 END) AS BASESUBST,
    (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (((P2.VLRVENDA + (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100) * ICM.ALIQSUBTRIB/100) - 
    (P2.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END) AS VLRSUBST,
    (PR.VLRVENDA/(1+(((CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (((P2.VLRVENDA + (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100) * ICM.ALIQSUBTRIB/100) - 
    (P2.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END)/P2.VLRVENDA)+((CASE WHEN PRO.TEMIPIVENDA = 'S' THEN NVL(I.PERCENTUAL,0) ELSE 0 END)/100)))) AS VLRBASE,
    (P2.VLRVENDA + ((CASE WHEN PRO.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) + (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (((P2.VLRVENDA + (CASE WHEN PRO.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100) * ICM.ALIQSUBTRIB/100) - 
    (P2.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END)) AS VLRTOTAL,
    P2.DISPONIVEL
FROM TAB_P2 P2
    INNER JOIN TGFPRO PRO ON PRO.CODPROD = P2.CODPROD
    INNER JOIN AD_TGFTABIPC PR ON PR.CODPROD = PRO.CODPROD
    LEFT JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
    LEFT JOIN TGFIPI I ON I.CODIPI = PRO.CODIPI
    LEFT JOIN TGFICM ICM ON ICM.IDALIQ = P2.IDALIQICMS
WHERE PRO.ATIVO = 'S'
ORDER BY
    GRU.AD_SEQAPRESENT, GRU.DESCRGRUPOPROD, PRO.DESCRPROD


---------------------------------------------------------------------------------------------------------
WITH TAB_ALIQ AS (
    SELECT
        I.IDALIQ, 
        I.CODTRIB,
        I.ALIQUOTA,
        I.ALIQSUBTRIB,
        I.TIPRESTRICAO, 
        I.TIPRESTRICAO2, 
        I.CODRESTRICAO, 
        I.CODRESTRICAO2,
        P.PRIORIDADE
    FROM TGFICM I, TGFPRI P
    WHERE I.UFORIG = 8
      AND I.UFDEST = 8
      AND I.TIPRESTRICAO = P.TIPRESTRICAO1
      AND I.TIPRESTRICAO2 = P.TIPRESTRICAO2
) 
SELECT * FROM TAB_ALIQ 
WHERE 
    (PRIORIDADE = 560 AND
    CODRESTRICAO = 18 AND
    CODRESTRICAO2 = 1723) OR
    (PRIORIDADE = 563 AND
    CODRESTRICAO = '39231090' AND
    CODRESTRICAO2 = 18) OR
    (PRIORIDADE = 564 AND
    CODRESTRICAO = 1723 AND
    CODRESTRICAO2 = -1) OR
    (PRIORIDADE = 565 AND
    CODRESTRICAO = '' AND
    CODRESTRICAO2 = '39231090') OR
    (PRIORIDADE = 566 AND
    CODRESTRICAO = '' AND
    CODRESTRICAO2 = -1) OR
    (PRIORIDADE = 567 AND
    CODRESTRICAO = -1 AND
    CODRESTRICAO2 = -1) OR
    (PRIORIDADE = 568 AND
    CODRESTRICAO = 1723 AND
    CODRESTRICAO2 = 1)