SELECT T.NOMETAB,
       T.DESCRTAB,
       M.NOMECAMPO,
       M.DESCRCAMPO,
       C.CONSTRAINT_NAME
  FROM USER_CONS_COLUMNS C,
       TDDTAB            T,
       TDDCAM            M
 WHERE C.CONSTRAINT_NAME like '%'||:CONS||'%'
   AND T.NOMETAB = C.TABLE_NAME
   AND M.NOMECAMPO = C.COLUMN_NAME
   AND M.NOMETAB = C.TABLE_NAME