="INSERT INTO TGFITE (NUNOTA, SEQUENCIA, CODEMP, CODPROD, CODVOL, CODLOCALORIG, USOPROD, QTDNEG, VLRUNIT, VLRTOT, ATUALESTOQUE, PENDENTE, STATUSNOTA) VALUES (233960, "&A2&", 1, "&C2&", 'UN', "&D2&", 'R', "&F2&", 1.00, "&D2&", -1, 'N', 'L');"

="INSERT INTO TGFITE (NUNOTA, SEQUENCIA, CODEMP, CODPROD, CODVOL, CODLOCALORIG, USOPROD, QTDNEG, VLRUNIT, VLRTOT, ATUALESTOQUE, PENDENTE, STATUSNOTA) VALUES (233962, "&A2&", 2, "&B2&", 'UN', 299000000, 'R', "&G2&", 1.00, "&G2&", 1, 'N', 'L');"



