UPDATE TGFICM SET ALIQUOTA = 19.50 
        WHERE UFORIG = 8 AND UFDEST = 8 AND ALIQUOTA = 19 AND ALIQSUBTRIB IS NULL;

UPDATE TGFICM SET ALIQSUBTRIB = 19.50 
        WHERE UFORIG = 8 AND UFDEST = 8 AND ALIQUOTA <> 19 AND ALIQSUBTRIB IS NOT NULL;