SELECT
    MBC.CODCTABCOINT  AS "Cod_Conta",
    BCO.NOMEBCO AS "Banco",
    CTA.CODCTABCO AS "Conta",
    MBC.DHCONCILIACAO AS "Dta_Conciliacao",
    FIN.DTNEG AS "Dta_Negociacao",
    FIN.DTVENC AS "Dta_Vencimento",
    FIN.NUMNOTA AS "Nro_NF-e",
    FIN.CODPARC AS "Cod_Parceiro",
    MBC.HISTORICO AS "Historico",
    TIT.DESCRTIPTIT AS "Tipo_Titulo",
    FIN.VLRDESDOB AS "Vlr_Titulo",
    FIN.VLRJURO AS "Vlr_Juro",
    FIN.VLRDESC AS "Vlr_Desc",
    CASE WHEN MBC.RECDESP=1 THEN VLRLANC ELSE 0 END AS "Credito",
    CASE WHEN MBC.RECDESP=-1 THEN VLRLANC ELSE 0 END AS "Debito",
    PAR.NOMEPARC AS "Parceiro",
    MBC.DTLANC AS "Dta_Baixa",
    MBC.NUMDOC AS "Nro_Documento",
    (SELECT CTA1.CODCTABCO FROM TGFMBC MBB, TSICTA CTA1
        WHERE MBC.NUMTRANSF = MBB.NUMTRANSF AND MBC.ORIGMOV = MBB.ORIGMOV AND MBC.RECDESP <> MBB.RECDESP AND MBB.CODCTABCOINT = CTA1.CODCTABCOINT) AS "Contra_Partida",
    CTA.DESCRICAO AS "Descricao_Conta",
    NAT.DESCRNAT AS "Descricao_Natureza",
    PRJ.IDENTIFICACAO AS "Projeto"
FROM TGFMBC /*CC (TOP, CODTIPOPER) (Conta Bancária, CODCTABCOINT) CC*/ MBC,
    TSICTA /*CC (Empresa, CODEMP) (Conta Bancária, CODCTABCOINT) (Conta Bancária, CODCTABCOINTREM) (Parceiro, CODPARC) CC*/ CTA,
    TSIBCO BCO,
    TGFFIN /*CC (Empresa, CODEMP) (Centro de Resultado, CODCENCUS) (Natureza, CODNAT) (Projeto, CODPROJ) (Parceiro, CODPARC) (TOP, CODTIPOPER) (Conta Bancária, CODCTABCOINT) CC*/ FIN,
    TGFTIT TIT,
    TGFPAR /*CC (Empresa, CODEMP) (Parceiro, CODPARC) (Parceiro, CODPARCMATRIZ) (Conta Bancária, CODCTABCOINT) CC*/ PAR,
    TGFNAT /*CC (Centro de Resultado, CODCENCUS) (Natureza, CODNAT) CC*/ NAT,
    TCSPRJ PRJ
WHERE
    FIN.CODTIPTIT = TIT.CODTIPTIT
    AND MBC.CODCTABCOINT = CTA.CODCTABCOINT
    AND CTA.CODBCO = BCO.CODBCO
    AND FIN.NUBCO(+) = MBC.NUBCO
    AND PRJ.CODPROJ = FIN.CODPROJ
    AND NVL(FIN.CODNAT,0) = NAT.CODNAT
    AND FIN.NUBCO = MBC.NUBCO
    AND MBC.NUBCO = FIN.NUBCO(+)
    AND PAR.CODPARC(+) = FIN.CODPARC
    AND ((MBC.CODCTABCOINT IN (1,3,4,5,6,8,9,12,13,100,101,102,103,104,105,106))
    AND (FIN.AD_ENVCONTAB = 'N' OR FIN.AD_ENVCONTAB IS NULL)
    AND MBC.DHCONCILIACAO >= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -2)) + 1)
    AND MBC.DHCONCILIACAO <= LAST_DAY(ADD_MONTHS(SYSDATE, -1)))
UNION ALL
SELECT
    FIN.CODCTABCOINT AS "Cod_Conta",
    null AS "Banco",
    null AS "Conta",
    null AS "Dta_Conciliacao",
    FIN.DTNEG AS "Dta_Negociacao",
    FIN.DTVENC AS "Dta_Vencimento",
    FIN.NUMNOTA AS "Nro_NF-e",
    FIN.CODPARC AS "Cod_Parceiro",
    FIN.HISTORICO AS "Historico",
    TIT.DESCRTIPTIT AS "Tipo_Titulo",
    FIN.VLRDESDOB AS "Vlr_Titulo",
    FIN.VLRJURO AS "Vlr_Juro",
    FIN.VLRDESC AS "Vlr_Desc",
    CASE WHEN FIN.RECDESP=1 THEN VLRDESDOB ELSE 0 END AS "Credito",
    CASE WHEN FIN.RECDESP=-1 THEN VLRDESDOB ELSE 0 END AS "Debito",
    PAR.NOMEPARC AS "Parceiro",
    FIN.DHBAIXA AS "Dta_Baixa",
    null AS "Nro_Documento",
    null AS "Contra_Partida",
    null AS "Descricao_Conta",
    NAT.DESCRNAT AS "Descricao_Natureza",
    PRJ.IDENTIFICACAO AS "Projeto"
FROM TGFFIN /*CC (Empresa, CODEMP) (Centro de Resultado, CODCENCUS) (Natureza, CODNAT) (Projeto, CODPROJ) (Parceiro, CODPARC) (TOP, CODTIPOPER) (Conta Bancária, CODCTABCOINT) CC*/ FIN,
    TGFTIT TIT,
    TGFPAR /*CC (Empresa, CODEMP) (Parceiro, CODPARC) (Parceiro, CODPARCMATRIZ) (Conta Bancária, CODCTABCOINT) CC*/ PAR,
    TGFNAT /*CC (Centro de Resultado, CODCENCUS) (Natureza, CODNAT) CC*/ NAT,
    TCSPRJ PRJ
WHERE
    FIN.CODTIPTIT = TIT.CODTIPTIT
    AND NVL(FIN.CODNAT,0) = NAT.CODNAT 
    AND PAR.CODPARC = FIN.CODPARC
    AND PRJ.CODPROJ = FIN.CODPROJ
    AND ((FIN.CODEMP = 2)
    AND (FIN.NUBCO IS NULL)
    AND (FIN.PROVISAO = 'N')
    AND (FIN.AD_ENVCONTAB = 'N' OR FIN.AD_ENVCONTAB IS NULL)
    AND (FIN.DHBAIXA >= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -2)) + 1))
    AND ( FIN.DHBAIXA <= LAST_DAY(ADD_MONTHS(SYSDATE, -1))))
ORDER BY "Cod_Conta", "Dta_Conciliacao", "Dta_Baixa"