SELECT
    MBC.CODCTABCOINT,
    BCO.NOMEBCO,
    CTA.CODCTABCO,
    MBC.DHCONCILIACAO,
    FIN.DTNEG,
    FIN.DTVENC,
    FIN.NUMNOTA,
    FIN.CODPARC,
    MBC.HISTORICO,
    TIT.DESCRTIPTIT,
    FIN.VLRDESDOB,
    FIN.VLRJURO,
    FIN.VLRDESC,
    CASE WHEN MBC.RECDESP=1 THEN VLRLANC ELSE 0 END As CREDITO,
    CASE WHEN MBC.RECDESP=-1 THEN VLRLANC ELSE 0 END As DEBITO,
    PAR.NOMEPARC,
    MBC.DTLANC,
    MBC.NUMDOC,
    (SELECT CTA1.CODCTABCO FROM TGFMBC MBB, TSICTA CTA1
        WHERE MBC.NUMTRANSF = MBB.NUMTRANSF AND MBC.ORIGMOV = MBB.ORIGMOV AND MBC.RECDESP <> MBB.RECDESP AND MBB.CODCTABCOINT = CTA1.CODCTABCOINT) As "Contra_Partida",
    CTA.DESCRICAO,
    NAT.DESCRNAT,
    PRJ.IDENTIFICACAO
FROM TGFMBC /*CC (TOP, CODTIPOPER) (Conta Bancária, CODCTABCOINT) CC*/ MBC ,
    TSICTA /*CC (Empresa, CODEMP) (Conta Bancária, CODCTABCOINT) (Conta Bancária, CODCTABCOINTREM) (Parceiro, CODPARC) CC*/
    CTA , TSIBCO BCO , TGFFIN /*CC (Empresa, CODEMP) (Centro de Resultado, CODCENCUS) (Natureza, CODNAT) (Projeto, CODPROJ) (Parceiro, CODPARC) (TOP, CODTIPOPER) (Conta Bancária, CODCTABCOINT) CC*/ FIN ,
    TGFTIT TIT , TGFPAR /*CC (Empresa, CODEMP) (Parceiro, CODPARC) (Parceiro, CODPARCMATRIZ) (Conta Bancária, CODCTABCOINT) CC*/ PAR ,
    TGFNAT /*CC (Centro de Resultado, CODCENCUS) (Natureza, CODNAT) CC*/ NAT,
    TCSPRJ PRJ
WHERE
    FIN.CODTIPTIT = TIT.CODTIPTIT
    AND MBC.CODCTABCOINT = CTA.CODCTABCOINT
    AND CTA.CODBCO = BCO.CODBCO
    AND FIN.NUBCO(+) = MBC.NUBCO
    AND PRJ.CODPROJ = FIN.CODPROJ
    AND NVL(FIN.CODNAT,0) = NAT.CODNAT
    AND FIN.NUBCO = MBC.NUBCO
    AND MBC.NUBCO = FIN.NUBCO(+)
    AND PAR.CODPARC(+) = FIN.CODPARC
    AND ((MBC.CODCTABCOINT IN (1,3,4,5,6,8,9,12,13,100,101,102,103,104,105,106))
    AND (FIN.AD_ENVCONTAB = 'N' OR FIN.AD_ENVCONTAB IS NULL)
    AND MBC.DHCONCILIACAO >= TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -2)) + 1)
    AND MBC.DHCONCILIACAO <= LAST_DAY(ADD_MONTHS(SYSDATE, -1)))
ORDER BY MBC.CODCTABCOINT, MBC.DHCONCILIACAO