CREATE OR REPLACE PROCEDURE "AD_STP_UPD_TABPRECO2" (
       P_CODUSU NUMBER,        -- Código do usuário logado
       P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
       P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
       P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
       FIELD_CODGRUPOPROD NUMBER;
       P_NUTAB NUMBER;
       
BEGIN

       DELETE FROM AD_TGFTABBASE;

       INSERT INTO AD_TGFTABBASE (CODPROD,VLRUNIT,VLRVENDA,BASEIPI,PERCIPI,VLRIPI,BASESUBST,VLRSUBST,VLRBASE,MVA)
       WITH TAB_P2 AS (
              SELECT
                     EXC.CODPROD AS CODPROD,
                     EXC.VLRVENDA AS VLRVENDA,
                     ITE.IDALIQICMS
              FROM TGFEXC EXC
                     LEFT JOIN TGFITE ITE ON ITE.CODPROD = EXC.CODPROD
              WHERE 
                     EXC.NUTAB = (SELECT MAX(NUTAB) FROM TGFTAB WHERE CODTAB = 2) AND
                     ITE.NUNOTA = 188538
       )
       SELECT
              P2.CODPROD,
              P2.VLRVENDA AS VLRUNIT,
              PR.VLRVENDA,
              (CASE WHEN P.TEMIPIVENDA = 'S' THEN P2.VLRVENDA ELSE 0 END) AS BASEIPI,
              (CASE WHEN P.TEMIPIVENDA = 'S' THEN NVL(I.PERCENTUAL,0) ELSE 0 END) AS PERCIPI,
              (CASE WHEN P.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END) AS VLRIPI,
              (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN 
                     ((P2.VLRVENDA + 
                            (CASE WHEN P.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100)) ELSE 0 END) AS BASESUBST,
              (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (((P2.VLRVENDA + (CASE WHEN P.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100) * ICM.ALIQSUBTRIB/100) - 
                     (P2.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END) AS VLRSUBST,
              (PR.VLRVENDA/(1+(((CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (((P2.VLRVENDA + (CASE WHEN P.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100) * ICM.ALIQSUBTRIB/100) - 
                     (P2.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END)/P2.VLRVENDA)+((CASE WHEN P.TEMIPIVENDA = 'S' THEN NVL(I.PERCENTUAL,0) ELSE 0 END)/100)))) AS VLRBASE,
              ICM.MARGLUCRO AS MVA
       FROM TAB_P2 P2
              INNER JOIN TGFPRO P ON P.CODPROD = P2.CODPROD
              LEFT JOIN AD_TGFTABIPC PR ON PR.CODPROD = P.CODPROD
              LEFT JOIN TGFIPI I ON I.CODIPI = P.CODIPI
              LEFT JOIN TGFICM ICM ON ICM.IDALIQ = P2.IDALIQICMS
       WHERE P.ATIVO = 'S';

       UPDATE AD_TGFPROTP P SET 
              P.MVA = (SELECT MVA FROM AD_TGFTABBASE WHERE CODPROD = P.CODPROD),
              P.STCALC = (SELECT VLRSUBST FROM AD_TGFTABBASE WHERE CODPROD = P.CODPROD),
              P.VLRTAB = (SELECT VLRBASE FROM AD_TGFTABBASE WHERE CODPROD = P.CODPROD)
       WHERE CODPROD > 0;

       SELECT MAX(NUTAB) INTO P_NUTAB FROM TGFTAB;

       INSERT INTO TGFTAB (NUTAB,CODTAB,DTVIGOR,DTALTER,CODTABORIG,UTILIZADECCUSTO)
       VALUES (P_NUTAB,2,SYSDATE,SYSDATE,2,'S');

       INSERT INTO TGFEXC (NUTAB,CODPROD,VLRVENDA,TIPO,CODLOCAL)
       SELECT 
              P_NUTAB,
              CODPROD,
              VLRBASE,
              'V',
              0
       FROM AD_TGFTABBASE;

END;
