CREATE OR REPLACE PROCEDURE "AD_STP_UPD_TGFTABIPC" (
       P_TIPOEVENTO INT,    -- Identifica o tipo de evento
       P_IDSESSAO VARCHAR2, -- Identificador da execução. Serve para buscar informações dos campos da execução.
       P_CODUSU INT         -- Código do usuário logado
) AS
       BEFORE_INSERT INT;
       AFTER_INSERT  INT;
       BEFORE_DELETE INT;
       AFTER_DELETE  INT;
       BEFORE_UPDATE INT;
       AFTER_UPDATE  INT;
       BEFORE_COMMIT INT;

       P_CODPROD NUMBER;
       P_GRUPO NUMBER;
       P_GRUPAI NUMBER;

BEGIN
       BEFORE_INSERT := 0;
       AFTER_INSERT  := 1;
       BEFORE_DELETE := 2;
       AFTER_DELETE  := 3;
       BEFORE_UPDATE := 4;
       AFTER_UPDATE  := 5;
       BEFORE_COMMIT := 10;

       IF P_TIPOEVENTO = AFTER_INSERT THEN
              P_CODPROD := EVP_GET_CAMPO_INT(P_IDSESSAO,'CODPROD');
              SELECT CODGRUPOPROD INTO P_GRUPO FROM TGFPRO WHERE CODPROD = P_CODPROD;
              SELECT CODGRUPAI INTO P_GRUPAI FROM TGFGRU WHERE CODGRUPOPROD = P_GRUPO;

              UPDATE AD_TGFTABIPC SET CODGRUPOPROD = P_GRUPO WHERE CODPROD = P_CODPROD;
              UPDATE AD_TGFTABIPC SET CODGRUPOPAI = P_GRUPAI WHERE CODPROD = P_CODPROD;

       END IF;

       IF P_TIPOEVENTO = AFTER_UPDATE THEN
              P_CODPROD := EVP_GET_CAMPO_INT(P_IDSESSAO,'CODPROD');
              SELECT CODGRUPOPROD INTO P_GRUPO FROM TGFPRO WHERE CODPROD = P_CODPROD;
              SELECT CODGRUPAI INTO P_GRUPAI FROM TGFGRU WHERE CODGRUPOPROD = P_GRUPO;

              UPDATE AD_TGFTABIPC SET CODGRUPOPROD = P_GRUPO WHERE CODPROD = P_CODPROD;
              UPDATE AD_TGFTABIPC SET CODGRUPOPAI = P_GRUPAI WHERE CODPROD = P_CODPROD;
       END IF;
END;