CREATE OR REPLACE PROCEDURE "AD_STP_LANCA_PROVISIONAMENTO" AS
BEGIN

    INSERT INTO TGFFIN (NUFIN,CODPARC,NUMNOTA,VLRDESDOB,RECDESP,DTNEG,DTVENCINIC,DTVENC,HISTORICO,CODBCO,CODTIPTIT,AD_CODDESPFIXA,AD_DESPFIXA,CODEMP,PROVISAO,CODTIPOPER,DHTIPOPER,DESDOBRAMENTO,CODNAT,DTALTER,DHMOV,CODPROJ)
    WITH TAB_FIN AS (
    SELECT 
        (SELECT MAX(NUFIN) FROM TGFFIN) AS NUFIN,
        DFX.CODPARC AS CODPARC,
        TO_CHAR(DFX.DTVENCINI, 'YYYYMM') AS NUMNOTA,
        DFX.VLRDESP AS VLRDESP,
        -1 AS RECDESP,
        TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS DTNEG,
        DFX.DTVENCINI AS DTVENCINI,
        (SELECT REPLACE(ADD_MONTHS(MAX(DTVENC),(
            CASE 
                WHEN DFX.TIPO = 1 THEN 1
                WHEN DFX.TIPO = 2 THEN 2
                WHEN DFX.TIPO = 3 THEN 3
                WHEN DFX.TIPO = 6 THEN 6
                WHEN DFX.TIPO = 12 THEN 12
            END)
        ),TO_CHAR(ADD_MONTHS(MAX(DTVENC),(
            CASE 
                WHEN DFX.TIPO = 1 THEN 1
                WHEN DFX.TIPO = 2 THEN 2
                WHEN DFX.TIPO = 3 THEN 3
                WHEN DFX.TIPO = 6 THEN 6
                WHEN DFX.TIPO = 12 THEN 12
            END)
        ),'DD'),TO_CHAR(DFX.DTVENCINI,'DD')) FROM TGFFIN WHERE AD_CODDESPFIXA = DFX.CODDESPFIXA) AS DTVENC,
        NVL(DFX.OBSDESP,'') AS HISTORICO,
        1 AS CODBCO,
        2 AS TIPTITULO,
        DFX.CODDESPFIXA AS CODDESPFIXA,
        'S' AS DESPFIXA,
        DFX.CODEMP AS CODEMP,
        'S' AS PROVISAO,
        DFX.CODTIPOPER AS CODTIPOPER,
        (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = DFX.CODTIPOPER) AS DHOPER,
        (SELECT COUNT(*) + 1 FROM TGFFIN WHERE AD_CODDESPFIXA = DFX.CODDESPFIXA) AS DESDOBRAMENTO,
        DFX.CODNAT AS CODNAT,
        TO_CHAR(SYSDATE, 'DD/MM/YYYY') AS DTALTER,
        SYSDATE AS DHMOV,
        DFX.CODPROJ AS CODPROJ
    FROM AD_TGFDFX DFX
    WHERE DFX.ATIVO = 'S' AND DESPSTATUS = 'A'
    HAVING (
        SELECT COUNT(AD_CODDESPFIXA) FROM TGFFIN
        WHERE   
            RECDESP = -1 AND
            DHBAIXA IS NULL AND
            PROVISAO = 'S' AND
            AD_DESPFIXA = 'S' AND
            AD_CODDESPFIXA IS NOT NULL AND
            AD_CODDESPFIXA = DFX.CODDESPFIXA
        ) <= (
        CASE 
            WHEN DFX.TIPO = 1 THEN 4
            WHEN DFX.TIPO = 2 THEN 3
            WHEN DFX.TIPO = 3 THEN 2
            WHEN DFX.TIPO = 6 THEN 1
            WHEN DFX.TIPO = 12 THEN 0
        END)
    GROUP BY 
        DFX.CODPARC,
        DFX.DTVENCINI,
        DFX.VLRDESP,
        DFX.DTVENCINI,
        DFX.OBSDESP,
        DFX.CODDESPFIXA,
        DFX.CODEMP,
        DFX.CODTIPOPER,
        DFX.CODNAT,
        DFX.CODPROJ,
        DFX.TIPO
    ) SELECT 
        NUFIN+ROWNUM,CODPARC,NUMNOTA,VLRDESP,RECDESP,DTNEG,DTVENCINI,DTVENC,HISTORICO,CODBCO,TIPTITULO,CODDESPFIXA,DESPFIXA,CODEMP,PROVISAO,CODTIPOPER,
        DHOPER,DESDOBRAMENTO,CODNAT,DTALTER,DHMOV,CODPROJ
    FROM TAB_FIN; 
    
END;