CREATE OR REPLACE PROCEDURE "AD_STP_UPD_TABPRECO2" (
    P_CODUSU NUMBER,        -- Código do usuário logado
    P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
    P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
    P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
    FIELD_CODPROD NUMBER;

BEGIN

    DELETE FROM AD_TGFTABBASE;

    /*ALIMENTA A TABELA INTERMEDIARIA AD_TGFTABBASE COM OS DADOS BASICO DOS PRODUTOS DA TABELA DE PREÇO 2 */

    INSERT INTO AD_TGFTABBASE (SEQUENCIA,CODPROD,GRUPOICMS,GRUPOICMS2,NCM,TOP,VLRUNIT,VLRVENDA,BASEIPI,PERCIPI,VLRIPI)
    WITH TAB_P2 AS (
        SELECT
            ROWNUM AS SEQUENCIA,
            EXC.CODPROD AS CODPROD,
            EXC.VLRVENDA AS VLRVENDA,
            PRO.GRUPOICMS,
            PRO.GRUPOICMS2,
            PRO.NCM,
            1723 AS TOP
    FROM TGFEXC EXC
            INNER JOIN TGFPRO PRO ON PRO.CODPROD = EXC.CODPROD
    WHERE 
            EXC.NUTAB = (SELECT MAX(NUTAB) FROM TGFTAB WHERE CODTAB = 2) AND
            PRO.ATIVO = 'S'
    )
    SELECT
    P2.SEQUENCIA,
    P2.CODPROD,
    P2.GRUPOICMS,
    P2.GRUPOICMS2,
    P2.NCM,
    P2.TOP,
    P2.VLRVENDA AS VLRUNIT,
    PR.VLRVENDA,
    (CASE WHEN P.TEMIPIVENDA = 'S' THEN P2.VLRVENDA ELSE 0 END) AS BASEIPI,
    (CASE WHEN P.TEMIPIVENDA = 'S' THEN NVL(I.PERCENTUAL,0) ELSE 0 END) AS PERCIPI,
    (CASE WHEN P.TEMIPIVENDA = 'S' THEN (P2.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END) AS VLRIPI
    FROM TAB_P2 P2
    INNER JOIN TGFPRO P ON P.CODPROD = P2.CODPROD
    LEFT JOIN AD_TGFTABIPC PR ON PR.CODPROD = P.CODPROD
    LEFT JOIN TGFIPI I ON I.CODIPI = P.CODIPI;

    /*ATUALIZA OS PRODUTOS NA TABELA AD_TGFTABBASE COM O IDALIQICMS*/

    UPDATE AD_TGFTABBASE T
    SET 
    T.IDALIQICMS = (
            WITH TAB_ALIQ AS (
            SELECT
                    I.IDALIQ, 
                    I.CODTRIB,
                    I.ALIQUOTA,
                    I.ALIQSUBTRIB,
                    I.TIPRESTRICAO, 
                    I.TIPRESTRICAO2, 
                    I.CODRESTRICAO, 
                    I.CODRESTRICAO2,
                    P.PRIORIDADE
            FROM TGFICM I, TGFPRI P
            WHERE I.UFORIG = 8
                    AND I.UFDEST = 8
                    AND I.TIPRESTRICAO = P.TIPRESTRICAO1
                    AND I.TIPRESTRICAO2 = P.TIPRESTRICAO2
            ) 
            SELECT IDALIQ FROM TAB_ALIQ 
            WHERE 
            (PRIORIDADE = 560 AND CODRESTRICAO = T.GRUPOICMS AND CODRESTRICAO2 = T.TOP) OR
            (PRIORIDADE = 563 AND CODRESTRICAO = T.NCM AND CODRESTRICAO2 = T.GRUPOICMS) OR
            (PRIORIDADE = 564 AND CODRESTRICAO = T.TOP AND CODRESTRICAO2 = -1) OR
            (PRIORIDADE = 565 AND CODRESTRICAO = NVL(T.GRUPOICMS2,'') AND CODRESTRICAO2 = T.NCM) OR
            (PRIORIDADE = 566 AND CODRESTRICAO = NVL(T.GRUPOICMS2,'') AND CODRESTRICAO2 = -1) OR
            (PRIORIDADE = 567 AND CODRESTRICAO = -1 AND CODRESTRICAO2 = -1) OR
            (PRIORIDADE = 568 AND CODRESTRICAO = T.TOP AND CODRESTRICAO2 = 1))
    WHERE T.CODPROD > 0;

    /*ATUALIZA A TABELA AD_TGFTABBASE COM OS VALORES DE BASESUBST, VLRSUBST, MVA E VLRBASE*/

    UPDATE AD_TGFTABBASE T
    SET
        T.BASESUBST = (
            SELECT 
                (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (
                    (T.VLRVENDA + 
                        (CASE WHEN P.TEMIPIVENDA = 'S' THEN (T.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1 + ICM.MARGLUCRO/100)) 
                    ELSE 0 END)
            FROM TGFPRO P
                LEFT JOIN TGFIPI I ON I.CODIPI = P.CODIPI
                LEFT JOIN TGFICM ICM ON ICM.IDALIQ = T.IDALIQICMS 
            WHERE P.CODPROD = T.CODPROD
        ),
        T.VLRSUBST = (
            SELECT 
                (CASE WHEN ICM.ALIQSUBTRIB > 0 THEN 
                    (((T.VLRVENDA + (CASE WHEN P.TEMIPIVENDA = 'S' THEN 
                        (T.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1 + ICM.MARGLUCRO/100) * ICM.ALIQSUBTRIB/100) - 
                            (T.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END)
            FROM TGFPRO P
                LEFT JOIN TGFIPI I ON I.CODIPI = P.CODIPI
                LEFT JOIN TGFICM ICM ON ICM.IDALIQ = T.IDALIQICMS 
            WHERE P.CODPROD = T.CODPROD        
        ),
        T.VLRBASE = (
            SELECT 
                (PR.VLRVENDA/(1+(((CASE WHEN ICM.ALIQSUBTRIB > 0 THEN (((T.VLRVENDA + 
                    (CASE WHEN P.TEMIPIVENDA = 'S' THEN (T.VLRVENDA * I.PERCENTUAL / 100) ELSE 0 END)) * (1+ICM.MARGLUCRO/100) * 
                        ICM.ALIQSUBTRIB/100) - (T.VLRVENDA * ICM.ALIQUOTA / 100)) ELSE 0 END)/T.VLRVENDA) +
                        ((CASE WHEN P.TEMIPIVENDA = 'S' THEN NVL(I.PERCENTUAL,0) ELSE 0 END)/100))))
            FROM TGFPRO P
                LEFT JOIN TGFIPI I ON I.CODIPI = P.CODIPI
                LEFT JOIN TGFICM ICM ON ICM.IDALIQ = T.IDALIQICMS 
                LEFT JOIN AD_TGFTABIPC PR ON PR.CODPROD = P.CODPROD
            WHERE P.CODPROD = T.CODPROD        
        ),
        T.MVA = (SELECT ICM.MARGLUCRO FROM TGFICM ICM WHERE ICM.IDALIQ = T.IDALIQICMS) 
    WHERE T.CODPROD > 0;

    /*ATUALIZAR A TABELA AD_TGFTABIPC COM OS VALORES CALCULADOS*/

    UPDATE AD_TGFTABIPC T
    SET
        MVA = (SELECT MVA FROM AD_TGFTABBASE WHERE CODPROD = T.CODPROD),
        STCALC = (SELECT VLRSUBST FROM AD_TGFTABBASE WHERE CODPROD = T.CODPROD),
        VLRTAB = (SELECT VLRBASE FROM AD_TGFTABBASE WHERE CODPROD = T.CODPROD)
    WHERE T.CODPROD > 0;

    /*INSERIR UMA NOVA LINHA NA TABELA DE PREÇO 2*/

    INSERT INTO TGFTAB (NUTAB,CODTAB,DTVIGOR,DTALTER,CODTABORIG,UTILIZADECCUSTO)
       VALUES ((SELECT MAX(NUTAB)+1 FROM TGFTAB),2,SYSDATE,SYSDATE,2,'S');

    INSERT INTO TGFEXC (NUTAB,CODPROD,VLRVENDA,TIPO,CODLOCAL)
       SELECT 
              (SELECT MAX(NUTAB) FROM TGFTAB WHERE CODTAB = 2),
              CODPROD,
              VLRBASE,
              'V',
              0
       FROM AD_TGFTABBASE
       WHERE VLRBASE > 0;
    
    P_MENSAGEM := 'Tabela de Preço Atualizada.';

END;