CREATE OR REPLACE PROCEDURE "AD_VALIDA_DADOS_ENTREGA" (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMERIC)
AS
BEGIN
DECLARE
  
  C_PROD INT := 0;
  C_COUNT INT := 0;

  BEGIN

    IF Stp_Get_Atualizando THEN
        RETURN;
    END IF;

    P_SUCESSO := 'S';

    SELECT COUNT(*) INTO C_PROD FROM TGFITE WHERE CODPROD IN (
      SELECT CODPROD FROM TGFPRO WHERE CODGRUPOPROD = 134003
    ); --VERIFICA SE HÁ PRODUTO POSTE NA NOTA
    SELECT COUNT(*) INTO C_COUNT FROM AD_TGFDEP WHERE NUNOTA = P_NUNOTA;  --VERIFICA SE OS DADOS DE ENTREGA FORAM INSERIDOS NA TABELA DE DADOS DE ENTREGA

    IF C_PROD > 0 THEN --SE HOUVER PRODUTOS NA NOTA 
      IF C_COUNT <= 0 THEN --E NÃO TIVER OS DADOS INSERIDOS NA TABELA AD_TGFDEP BLOQUEIA
        P_SUCESSO := 'N';
        P_MENSAGEM := 'Dados de Entrega para Poste não foram informados. Por favor informar através da opção "Dados Entrega Poste" através do ícone "Ações".';
      END IF;
    END IF;
  END;

END;