-- DADOS FINANCEIROS RESUMIDOS
SELECT
    CODNAT,
    MAX(DESCRNAT) AS DESCRNAT,
    SUM(VLRDESDOB) AS VALOR,
    AD_GOLFIX,
    (SUM(VLRDESDOB) / 
        (SELECT SUM(VGF.VLRDESDOB * VGF.RECDESP)
        FROM VGFFINRAT VGF
        WHERE (VGF.DTNEG BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY'))
            AND (VGF.CODEMP = 1) AND VGF.RECDESP <> 0 AND VGF.PROVISAO = 'N' AND VGF.CODNAT LIKE '1010%') * 100) AS VERTICAL,
    CASE WHEN CODNAT = '9999999' THEN 'BLUE' ELSE 'BLACK' END AS FGCOLOR
FROM (
    SELECT
        VGFFINRAT.CODNAT AS CODNAT,
        NAT.DESCRNAT,
        SUM(VGFFINRAT.VLRDESDOB * VGFFINRAT.RECDESP) AS VLRDESDOB,
        (CASE WHEN NAT.AD_GOLFIX = 'S' THEN 'SIM' ELSE 'NÃO' END) AS AD_GOLFIX
    FROM VGFFINRAT
        INNER JOIN TGFNAT NAT ON NAT.CODNAT = VGFFINRAT.CODNAT
    WHERE (VGFFINRAT.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN)
        AND (VGFFINRAT.CODEMP IN :CODEMP)
        AND VGFFINRAT.RECDESP <> 0
        AND VGFFINRAT.PROVISAO = 'N'
    GROUP BY VGFFINRAT.CODNAT, NAT.DESCRNAT, NAT.AD_GOLFIX
) 
GROUP BY CODNAT, CASE WHEN CODNAT = '9999999' THEN 'BLUE' ELSE 'GREEN' END, AD_GOLFIX

UNION ALL

-- DADOS DISTINTOS DE CODNATPAI COM VALOR AGREGADO (SEGUNDO NÍVEL)
SELECT
    NAT.CODNATPAI AS CODNAT,
    NAT2.DESCRNAT AS DESCRNAT,
    SUM(VGFFINRAT.VLRDESDOB * VGFFINRAT.RECDESP) AS VALOR,
    (CASE WHEN NAT2.AD_GOLFIX = 'S' THEN 'SIM' ELSE 'NÃO' END) AS AD_GOLFIX,
    (SUM(VGFFINRAT.VLRDESDOB * VGFFINRAT.RECDESP) / 
        (SELECT SUM(VGF.VLRDESDOB * VGF.RECDESP)
        FROM VGFFINRAT VGF
        WHERE (VGF.DTNEG BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY'))
            AND (VGF.CODEMP = 1) AND VGF.RECDESP <> 0 AND VGF.PROVISAO = 'N' AND VGF.CODNAT LIKE '1010%') * 100) AS VERTICAL,
    'GREEN' AS FGCOLOR
FROM TGFNAT NAT
    INNER JOIN TGFNAT NAT2 ON NAT.CODNATPAI = NAT2.CODNAT
    INNER JOIN VGFFINRAT ON NAT.CODNAT = VGFFINRAT.CODNAT
WHERE (VGFFINRAT.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN)
    AND (VGFFINRAT.CODEMP IN :CODEMP)
    AND VGFFINRAT.RECDESP <> 0
    AND VGFFINRAT.PROVISAO = 'N'
GROUP BY NAT.CODNATPAI, NAT2.DESCRNAT, NAT2.AD_GOLFIX

UNION ALL

-- DADOS DISTINTOS DE CODNATPAI COM VALOR AGREGADO (TERCEIRO NÍVEL)
SELECT
    NAT3.CODNAT AS CODNAT,
    NAT3.DESCRNAT AS DESCRNAT,
    SUM(VGFFINRAT.VLRDESDOB * VGFFINRAT.RECDESP) AS VALOR,
    (CASE WHEN NAT3.AD_GOLFIX = 'S' THEN 'SIM' ELSE 'NÃO' END) AS AD_GOLFIX,
    (SUM(VGFFINRAT.VLRDESDOB * VGFFINRAT.RECDESP) / 
        (SELECT SUM(VGF.VLRDESDOB * VGF.RECDESP)
        FROM VGFFINRAT VGF
        WHERE (VGF.DTNEG BETWEEN TO_DATE('01/06/2024', 'DD/MM/YYYY') AND TO_DATE('30/06/2024', 'DD/MM/YYYY'))
            AND (VGF.CODEMP = 1) AND VGF.RECDESP <> 0 AND VGF.PROVISAO = 'N' AND VGF.CODNAT LIKE '1010%') * 100) AS VERTICAL,
    'GREEN' AS FGCOLOR
FROM TGFNAT NAT
    INNER JOIN TGFNAT NAT2 ON NAT.CODNATPAI = NAT2.CODNAT
    INNER JOIN TGFNAT NAT3 ON NAT2.CODNATPAI = NAT3.CODNAT
    --INNER JOIN TGFNAT NAT4 ON NAT3.CODNATPAI = NAT4.CODNAT
    INNER JOIN VGFFINRAT ON NAT.CODNAT = VGFFINRAT.CODNAT
WHERE (VGFFINRAT.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN)
    AND (VGFFINRAT.CODEMP IN :CODEMP)
    AND VGFFINRAT.RECDESP <> 0
    AND VGFFINRAT.PROVISAO = 'N'
GROUP BY NAT3.CODNAT, NAT3.DESCRNAT, NAT3.AD_GOLFIX

UNION ALL

-- (-) DESPESAS OPERACIONAIS
SELECT
    999997 AS CODNAT,
    '(-) DESPESAS OPERACIONAIS' AS DESCRNAT,
    SUM(VGF.VLRDESDOB * VGF.RECDESP) AS VALOR,
    NULL AS AD_GOLFIX,
    NULL AS VERTICAL,
    'RED' AS FGCOLOR
FROM VGFFINRAT VGF
WHERE (VGF.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN)
    AND (VGF.CODEMP IN :CODEMP) AND VGF.RECDESP <> 0 AND VGF.PROVISAO = 'N' AND 
    ((VGF.CODNAT LIKE '2%' AND VGF.CODNAT NOT LIKE '202%') OR
    (VGF.CODNAT LIKE '3%' AND VGF.CODNAT NOT LIKE '305%') OR
    VGF.CODNAT LIKE '4%')

UNION ALL

--(=) RECEITA OPERACIONAL LIQUIDA
SELECT
    999998 AS CODNAT,
    '(=) RECEITA OPERACIONAL LIQUIDA' AS DESCRNAT,
    SUM(VGF.VLRDESDOB * VGF.RECDESP) AS VALOR,
    NULL AS AD_GOLFIX,
    NULL AS VERTICAL,
    'RED' AS FGCOLOR
FROM VGFFINRAT VGF
WHERE (VGF.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN)
    AND (VGF.CODEMP IN :CODEMP) AND VGF.RECDESP <> 0 AND VGF.PROVISAO = 'N' AND 
    (VGF.CODNAT LIKE '1%' OR
    VGF.CODNAT LIKE '305%')

UNION ALL

--(=) LUCRO BRUTO
SELECT
    999998 AS CODNAT,
    '(=) LUCRO BRUTO' AS DESCRNAT,
    SUM(VGF.VLRDESDOB * VGF.RECDESP) AS VALOR,
    NULL AS AD_GOLFIX,
    NULL AS VERTICAL,
    'RED' AS FGCOLOR
FROM VGFFINRAT VGF
WHERE (VGF.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN)
    AND (VGF.CODEMP IN :CODEMP) AND VGF.RECDESP <> 0 AND VGF.PROVISAO = 'N' AND 
    (VGF.CODNAT LIKE '1%' OR
    VGF.CODNAT LIKE '305%' OR
    VGF.CODNAT LIKE '202%')
ORDER BY 1