CREATE OR REPLACE VIEW AD_TGFATR (NUFIN, CODPARC, CODTIPTIT, DTNEG, DTVENC) AS
SELECT
    F.NUFIN, F.CODPARC, F.CODTIPTIT, F.DTNEG, F.DTVENC
FROM TGFFIN F
    LEFT JOIN TGFTOP T ON T.CODTIPOPER = F.CODTIPOPER
    LEFT JOIN TGFPAR P ON P.CODPARC = F.CODPARC
WHERE
    F.PROVISAO = 'N' AND
    F.RECDESP = 1 AND
    F.DHBAIXA IS NULL AND
    T.GRUPO NOT LIKE 'Ajustes' AND
    F.CODPARC NOT IN (0,1,7,9,21452) AND
    P.CLIENTE = 'S' AND P.USUARIO <> 'S' AND
    F.CODTIPTIT NOT IN (16,17)
HAVING
    (CASE 
        WHEN TO_CHAR(F.DTVENC, 'D') = 7 THEN
            F.DTVENC + 2
        WHEN TO_CHAR(F.DTVENC, 'D') = 1 THEN
            F.DTVENC + 1 
        WHEN TO_CHAR(F.DTVENC, 'DD/MM/YYYY') IN 
            (SELECT TO_CHAR(DTFERIADO, 'DD/MM/YYYY') FROM TSIFER WHERE TO_CHAR(DTFERIADO, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')) AND TO_CHAR(F.DTVENC, 'D') = 6 THEN
            F.DTVENC + 3
        WHEN TO_CHAR(F.DTVENC, 'DD/MM/YYYY') IN 
            (SELECT TO_CHAR(DTFERIADO, 'DD/MM/YYYY') FROM TSIFER WHERE TO_CHAR(DTFERIADO, 'YYYY') = TO_CHAR(SYSDATE, 'YYYY')) THEN
            F.DTVENC + 1
        WHEN F.CODBCO = 1 AND F.CODTIPTIT = 4 THEN
            (CASE WHEN TO_CHAR(F.DTVENC, 'D') = 6 THEN F.DTVENC + 3 ELSE F.DTVENC + 1 END)
        WHEN F.CODBCO = 33 AND F.CODTIPTIT = 4 THEN
            (CASE WHEN TO_CHAR(F.DTVENC, 'D') = 6 THEN F.DTVENC + 3 ELSE F.DTVENC + 1 END)
        WHEN F.CODBCO = 341 AND F.CODTIPTIT = 4 THEN
            (CASE WHEN TO_CHAR(F.DTVENC, 'D') = 6 THEN F.DTVENC + 3 ELSE F.DTVENC + 1 END)
        ELSE F.DTVENC + 1 END) < TRUNC(SYSDATE)
GROUP BY
    F.CODPARC, F.NUFIN, F.DTNEG, F.DTVENC, F.CODTIPTIT, F.CODBCO
ORDER BY
    F.DTVENC, F.DTNEG, F.NUFIN, F.CODPARC