CREATE OR REPLACE PROCEDURE SANKHYA.AD_ATUALIZA_STATUS_OS (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS
BEGIN
	
	DECLARE
	
		V_TOP NUMBER;
		V_STATUSNOTA VARCHAR2(1);
        V_PEDORIG NUMBER;
        V_ORCAMORIG NUMBER;
        V_USUINCORCAM NUMBER;

        C_NROITENS INT;
        C_NROITENSP INT;
  	
	BEGIN

		P_SUCESSO := 'S';

		SELECT CODTIPOPER INTO V_TOP FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
		SELECT STATUSNOTA INTO V_STATUSNOTA FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
        SELECT COUNT(CODPROD) INTO C_NROITENS FROM TGFITE WHERE NUNOTA = P_NUNOTA;
   
		IF V_TOP = 2000 OR V_TOP = 2005 THEN --Aguardando Instalação
			UPDATE TGFCAB SET AD_STATUS = '2' WHERE NUNOTA = P_NUNOTA;
		
			INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
			VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO ORÇAMENTO', 'ORÇAMENTO NRO: ' || P_NUNOTA || ' CONFIRMADO. AGUARDANDO INSTALAÇÃO!!', '', 'PERSONALIZADO', 3 , 36, NULL, 'P' , SYSDATE , 1 , NULL, '', '', NULL);

		END IF;
	
		IF V_TOP = 2006 THEN --Aguardando Faturamento
			UPDATE TGFCAB SET AD_STATUS = '4' WHERE NUNOTA = P_NUNOTA;
		
			INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
			VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO PEDIDO', 'PEDIDO NRO: ' || P_NUNOTA || ' CONFIRMADO. AGUARDANDO FATURAMENTO!!', '', 'PERSONALIZADO', 3 , 24, NULL, 'P' , SYSDATE , 1 , NULL, '', '', NULL);

            FOR I IN 1..C_NROITENS
            LOOP
                SELECT NVL(NUNOTAORIG,0) INTO V_PEDORIG FROM TGFVAR WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
                IF V_PEDORIG <> 0 THEN 
                    UPDATE TGFCAB SET AD_STATUS = '4' WHERE NUNOTA = V_PEDORIG;
                END IF;
            END LOOP;

		END IF;

		IF V_TOP = 2003 OR V_TOP = 2013 OR V_TOP = 2012 OR V_TOP = 2026 THEN --Faturado
			UPDATE TGFCAB SET AD_STATUS = '5' WHERE NUNOTA = P_NUNOTA;
		
			INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
			VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO PEDIDO', 'NOTA NRO: ' || P_NUNOTA || 'CONFIRMADA!!', '', 'PERSONALIZADO', 3 , NULL, NULL, 'P' , SYSDATE , 1 , NULL, '', '', NULL);

            FOR I IN 1..C_NROITENS
            LOOP
                SELECT NVL(NUNOTAORIG,0) INTO V_PEDORIG FROM TGFVAR WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
                IF V_PEDORIG <> 0 THEN 
                    UPDATE TGFCAB SET AD_STATUS = '5' WHERE NUNOTA = V_PEDORIG;
                    SELECT COUNT(CODPROD) INTO C_NROITENSP FROM TGFITE WHERE NUNOTA = V_PEDORIG;

                    FOR J IN 1..C_NROITENSP
                    LOOP
                        SELECT NVL(NUNOTAORIG,0) INTO V_ORCAMORIG FROM TGFVAR WHERE NUNOTA = V_PEDORIG AND SEQUENCIA = I;
                        IF V_ORCAMORIG <> 0 THEN 
                            UPDATE TGFCAB SET AD_STATUS = '5' WHERE NUNOTA = V_ORCAMORIG;

                            SELECT CODUSUINC INTO V_USUINCORCAM FROM TGFCAB WHERE NUNOTA = V_ORCAMORIG;

                            INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
                            VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO PEDIDO', 'NOTA NRO.: ' || P_NUNOTA || 'EMITIDA PARA O ORÇAMENTO ORIGEM NRO.: ' || V_ORCAMORIG, '', 'PERSONALIZADO', 3 , V_USUINCORCAM, NULL, 'P' , SYSDATE , 1 , NULL, '', '',NULL);                            
                        END IF;
                    END LOOP;
                END IF;
            END LOOP;

		END IF;
	
	END;
   
END AD_ATUALIZA_STATUS_CONFIRMACAO;