CREATE OR REPLACE PROCEDURE SANKHYA."AD_ATUALIZAR_STATUS_PEDIDO" (
       P_TIPOEVENTO INT,    -- Identifica o tipo de evento
       P_IDSESSAO VARCHAR2, -- Identificador da execução. Serve para buscar informações dos campos da execução.
       P_CODUSU INT         -- Código do usuário logado
) AS
       BEFORE_INSERT INT;
       AFTER_INSERT  INT;
       BEFORE_DELETE INT;
       AFTER_DELETE  INT;
       BEFORE_UPDATE INT;
       AFTER_UPDATE  INT;
       BEFORE_COMMIT INT;
      
       	V_NUNOTA NUMBER;
      	V_TIPMOV VARCHAR2(1);
		V_NROITENS INT;
		V_PEDORIG NUMBER;
		V_PENDENTE VARCHAR2(1);
		V_NROCONF NUMBER;
      
      
BEGIN
       BEFORE_INSERT := 0;
       AFTER_INSERT  := 1;
       BEFORE_DELETE := 2;
       AFTER_DELETE  := 3;
       BEFORE_UPDATE := 4;
       AFTER_UPDATE  := 5;
       BEFORE_COMMIT := 10;
       

	IF P_TIPOEVENTO = AFTER_UPDATE THEN
		V_NUNOTA := EVP_GET_CAMPO_INT(P_IDSESSAO, 'NUNOTA');	
		SELECT TIPMOV INTO V_TIPMOV FROM TGFCAB WHERE NUNOTA = V_NUNOTA;
		SELECT PENDENTE INTO V_PENDENTE FROM TGFCAB WHERE NUNOTA = V_NUNOTA;
		SELECT NUCONFATUAL INTO V_NROCONF FROM TGFCAB WHERE NUNOTA = V_NUNOTA;
		SELECT COUNT(CODPROD) INTO V_NROITENS FROM TGFITE WHERE NUNOTA = V_NUNOTA;
	
		IF V_TIPMOV = 'P' AND V_PENDENTE = 'S' AND V_NROCONF IS NOT NULL THEN
			UPDATE TGFCAB SET AD_STATUSPEDIDO = 'PFAT' WHERE NUNOTA = V_NUNOTA;
		END IF;
	
	END IF;

END;