CREATE OR REPLACE PROCEDURE "AD_ATUALIZA_CONTA_BANCO" (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS

    DECLARE 
        V_NUFIN NUMBER;
        V_EMP NUMBER;
        V_TIPTITULO NUMBER;
        V_BANCO NUMBER;

    BEGIN
        P_SUCESSO := 'S';

        SELECT CODEMP INTO V_EMP FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
        SELECT CODTIPVENDA INTO V_TIPNEGOC FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
        SELECT CODTIPTIT INTO V_TIPTITULO FROM TGFTPV WHERE CODTIPVENDA = V_TIPNEGOC;
        SELECT TIPMOV INTO V_TIPMOV FROM TGFCAB WHERE NUNOTA = P_NUNOTA;

        IF V_TIPMOV = 'P' OR V_TIPMOV = 'V' THEN
        
            IF V_EMP = 1 AND V_TIPTITULO = 4 THEN
                SELECT CODBCO INTO V_BANCO FROM TSICTA WHERE CODCTABCOINT = 6;

                UPDATE TGFFIN SET CODCTABCOINT = 6, CODBCO = V_BANCO WHERE NUFIN = V_NUFIN;

            END IF;

            IF V_EMP = 2 AND V_TIPTITULO = 4 THEN
                SELECT CODBCO INTO V_BANCO FROM TSICTA WHERE CODCTABCOINT = 3;

                UPDATE TGFFIN SET CODCTABCOINT = 3, CODBCO = V_BANCO WHERE NUFIN = V_NUFIN;
                
            END IF;

            IF V_EMP = 3 AND V_TIPTITULO = 4 THEN
                SELECT CODBCO INTO V_BANCO FROM TSICTA WHERE CODCTABCOINT = 1;

                UPDATE TGFFIN SET CODCTABCOINT = 1, CODBCO = V_BANCO WHERE NUFIN = V_NUFIN;
                
            END IF;
            
        END IF;
    END;
END AD_ATUALIZA_CONTA_BANCO;