CREATE OR REPLACE PROCEDURE         AD_ATUALIZA_STATUS_PED (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS
BEGIN
	
	DECLARE
	
		V_PEDIDO NUMBER;
		V_COTACAO NUMBER;
		V_TIPMOV VARCHAR2(1);
		V_NROITENS INT;
		V_PEDORIG NUMBER;
		V_STATUSNOTA VARCHAR2(1);
		V_STATUSNFE VARCHAR2(1);
		C_COT INT := 0;
  	
	BEGIN

		P_SUCESSO := 'S';

		SELECT TIPMOV INTO V_TIPMOV FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
		SELECT STATUSNOTA INTO V_STATUSNOTA FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
		SELECT STATUSNFE INTO V_STATUSNFE FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
		SELECT COUNT(CODPROD) INTO V_NROITENS FROM TGFITE WHERE NUNOTA = P_NUNOTA;
   
		IF V_TIPMOV = 'O' THEN --Em Produção
			SELECT COUNT(*) INTO C_COT FROM TGFITC WHERE NUNOTACPA = P_NUNOTA;

			IF C_COT > 0 THEN
				SELECT MAX(NUMCOTACAO) INTO V_COTACAO FROM TGFITC WHERE NUNOTACPA = P_NUNOTA;
				SELECT NUNOTAORIG INTO V_PEDIDO FROM TGFCOT WHERE NUMCOTACAO = V_COTACAO;
					
				UPDATE TGFCAB SET AD_STATUSPEDIDO = 'PROD' WHERE NUNOTA = V_PEDIDO;
			
				INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
				VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO PEDIDO COMPRA', 'PEDIDO DE COMPRA NRO: ' || P_NUNOTA|| ' GERADO PARA A COTAÇÃO ' || V_COTACAO, '', 'PERSONALIZADO', 3 , NULL, 7, 'P' , SYSDATE , 1 , NULL, '', '', NULL);
			
				INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
				VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO PEDIDO COMPRA', 'PEDIDO DE COMPRA NRO: ' || P_NUNOTA|| ' GERADO PARA A COTAÇÃO ' || V_COTACAO, '', 'PERSONALIZADO', 3 , 9, NULL, 'P' , SYSDATE , 1 , NULL, '', '', NULL);
			END IF;
		   
		END IF;
	
		IF V_TIPMOV = 'C' THEN --Em Separação 
			FOR I IN 1..V_NROITENS
			LOOP
				SELECT NUNOTAORIG INTO V_PEDORIG FROM TGFVAR WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
				SELECT COUNT(*) INTO C_COT FROM TGFITC WHERE NUNOTACPA = V_PEDORIG;

				IF C_COT > 0 THEN
					SELECT MAX(NUMCOTACAO) INTO V_COTACAO FROM TGFITC WHERE NUNOTACPA = V_PEDORIG;
					SELECT NUNOTAORIG INTO V_PEDIDO FROM TGFCOT WHERE NUMCOTACAO = V_COTACAO;
					
					UPDATE TGFCAB SET AD_STATUSPEDIDO = 'SEPR' WHERE NUNOTA = V_PEDIDO;
					
					INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
					VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO NOTA COMPRA', 'ENTRADA DA NOTA DE COMPRA NRO: ' || P_NUNOTA|| ' PARA O PEDIDO ' || V_PEDORIG || ' CONFIRMADA COM SUCESSO!', '', 'PERSONALIZADO', 3 , NULL, 11, 'P' , SYSDATE , 1 , NULL, '', '', NULL);
				
					INSERT INTO TSIAVI (NUAVISO, TITULO, DESCRICAO, SOLUCAO, IDENTIFICADOR, IMPORTANCIA, CODUSU, CODGRUPO, TIPO, DHCRIACAO, CODUSUREMETENTE, NUAVISOPAI, DTEXPIRACAO, DTNOTIFICACAO, ORDEM) 
					VALUES((SELECT MAX(NUAVISO)+1 FROM TSIAVI), 'NOTIFICAÇÃO NOTA COMPRA', 'ENTRADA DA NOTA DE COMPRA NRO: ' || P_NUNOTA|| ' PARA O PEDIDO ' || V_PEDORIG || ' CONFIRMADA COM SUCESSO!', '', 'PERSONALIZADO', 3 , 9, NULL, 'P' , SYSDATE , 1 , NULL, '', '', NULL);
			   	END IF;
			END LOOP;   
		END IF;
	
		IF V_TIPMOV = 'V' THEN --Faturado
			FOR I IN 1..V_NROITENS
			LOOP
				SELECT NUNOTAORIG INTO V_PEDORIG FROM TGFVAR WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
								
				UPDATE TGFCAB SET AD_STATUSPEDIDO = 'FATC' WHERE NUNOTA = V_PEDORIG;

			END LOOP;
		END IF;
	
END;
   
END AD_ATUALIZA_STATUS_PED;