CREATE OR REPLACE PROCEDURE TESTE."AD_INSERI_PROD_SERV" (
       P_CODUSU NUMBER,        -- Código do usuário logado
       P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
       P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
       P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
	FIELD_NUMCONTRATO NUMBER;

	V_PSCPROD NUMBER;
	V_PSCIMPRNOTA VARCHAR2(1);
	V_PSCNUMCONTRATO NUMBER;
	V_PSCSITPROD VARCHAR2(20);
	V_PSCTOPFATURCON NUMBER;

	V_PRECODPROD NUMBER;
	V_PRECODSERV NUMBER;
	V_PRENUMCONTRATO NUMBER;
	V_PREREFERENCIA DATE;
	V_PREVALOR NUMBER;
	
	V_GRUPECON NUMBER;
	V_CUSTO NUMBER;

	BEGIN
		
	    FOR I IN 1..P_QTDLINHAS
	    LOOP
	        FIELD_NUMCONTRATO := ACT_INT_FIELD(P_IDSESSAO, I, 'NUMCONTRATO');
	
	        SELECT AD_PSCCODPROD INTO V_PSCPROD FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PSCIMPRNOTA INTO V_PSCIMPRNOTA FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PSCNUMCONTRATO INTO V_PSCNUMCONTRATO FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PSCSITPROD INTO V_PSCSITPROD FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PSCTOPFATURCON INTO V_PSCTOPFATURCON FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	
	        SELECT AD_PRECODPROD INTO V_PRECODPROD FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO; 
	        SELECT AD_PRECODSERV INTO V_PRECODSERV FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PRENUMCONTRATO INTO V_PRENUMCONTRATO FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PREREFERENCIA INTO V_PREREFERENCIA FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	        SELECT AD_PREVALOR INTO V_PREVALOR FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;

			SELECT AD_GEC INTO V_GRUPECON FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
			SELECT AD_PERCCUSTO INTO V_CUSTO FROM TCSCON WHERE NUMCONTRATO = FIELD_NUMCONTRATO;
	
	        INSERT INTO TCSPSC (CODPROD,IMPRNOTA,NUMCONTRATO,SITPROD,TOPFATURCON)
	        VALUES (V_PSCPROD,V_PSCIMPRNOTA,V_PSCNUMCONTRATO,V_PSCSITPROD,V_PSCTOPFATURCON);
	
	        INSERT INTO TCSPRE (CODPROD,CODSERV,NUMCONTRATO,REFERENCIA,VALOR)
	        VALUES (V_PRECODPROD,V_PRECODSERV,V_PRENUMCONTRATO,V_PREREFERENCIA,V_PREVALOR);

			INSERT INTO TCSGEC (CODPARC,NUMCONTRATO,PERCUSTO)
			VALUES (V_GRUPECON,FIELD_NUMCONTRATO,V_CUSTO);
	
	    END LOOP;
	
	    P_MENSAGEM := 'PROCESSO FINALIZADO COM SUCESSO!';
	   
	END;
	