CREATE OR REPLACE PROCEDURE TESTE.AD_LANCA_TRANFERENCIA (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS 
BEGIN
	
DECLARE

	V_CODPROD NUMBER;
	V_NUNOTA NUMBER;
	V_QTDNEG NUMBER;
	V_NROITENS INT;
	V_CONTROLE VARCHAR2(50);
	V_LOCAL NUMBER;
	V_CODVOL VARCHAR(5);
	V_TRANF INT := 0;
	V_CODEMP NUMBER;
	V_USUINC NUMBER;
	V_CODPARC NUMBER;
	V_QTDTRANSF NUMBER;
	V_SEQ INT := 0;
	V_USOPROD VARCHAR2(2);
	V_TEMEST VARCHAR2(1);
	V_QTDDISPONIVEL NUMBER;

BEGIN
	
	P_SUCESSO := 'S';
	SELECT NVL(MAX(NUNOTA),0)+1 INTO V_NUNOTA FROM TGFCAB;
	SELECT COUNT(CODPROD) INTO V_NROITENS FROM TGFITE WHERE NUNOTA = P_NUNOTA;
	SELECT CODEMP INTO V_CODEMP FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
	SELECT CODUSUINC INTO V_USUINC FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
	SELECT CODPARC INTO V_CODPARC FROM TSIEMP WHERE CODEMP = V_CODEMP;


	BEGIN
		FOR I IN 1..V_NROITENS --VERIFICA SE O PRODUTO TEM ESTOQUE DISPONÍVEL SUFICIENTE
		LOOP
		    SELECT CODPROD INTO V_CODPROD FROM TGFITE WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
		   	SELECT CONTROLE INTO V_CONTROLE FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   	SELECT CODLOCALORIG INTO V_LOCAL FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		    SELECT QTDNEG INTO V_QTDNEG FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   	SELECT (CASE WHEN COUNT(CODPROD) > 0 THEN 'S' ELSE 'N' END) INTO V_TEMEST FROM TGFEST WHERE CODPROD = V_CODPROD; --VERIFICA SE O PRODUTO TEM LINHA NA TGFEST
			
		   	IF V_TEMEST = 'S' THEN --SE HOUVER LINHA NA TGFEST VERIFICA A O ESTOQUE DISPONÍVEL
		   		SELECT (ESTOQUE - RESERVADO) INTO V_QTDDISPONIVEL FROM TGFEST WHERE CODPROD = V_CODPROD AND CONTROLE = V_CONTROLE AND CODLOCAL = V_LOCAL;
		   	ELSE -- SE NÃO HOUVER INSERE UM REGISTRO E FAZ PEGA O DISPONÍVEL
		   		INSERT INTO TGFEST
					(CODEMP, CODLOCAL, CODPROD, CONTROLE, RESERVADO, ESTMIN, ESTMAX, ATIVO, CODBARRA, DTVAL, TIPO, CODPARC, PERCPUREZA, PERCGERMIN, ESTOQUE, DTFABRICACAO, STATUSLOTE, MD5PAF, DTENTRADA, QTDPEDPENDEST, WMSBLOQUEADO, PERCVC, CODAGREGACAO)
					VALUES(3, V_LOCAL, V_CODPROD, V_CONTROLE, V_QTDNEG, 0, 0, 'S', NULL, NULL, 'P', 0, NULL, NULL, 0, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL);
				SELECT (ESTOQUE - RESERVADO) INTO V_QTDDISPONIVEL FROM TGFEST WHERE CODPROD = V_CODPROD AND CONTROLE = V_CONTROLE AND CODLOCAL = V_LOCAL;
			END IF;
		   
		    IF V_QTDNEG > V_QTDDISPONIVEL THEN
		        V_TRANF := V_TRANF + 1; --SOMA 1 NA CONTAGEM PARA CADA PRODUTO COM ESTOQUE INSUFICIENTE
		    END IF;
		END LOOP;

		IF V_TRANF > 0 THEN --SE HOUVER AO MENOS 1 PRODUTO COM ESTOQUE INSUFICIENTE SERÁ LANÇADO UMA NOTA DE TRANSFERENCIA
		    INSERT INTO TGFCAB (NUNOTA,CODEMP,DTNEG,CODEMPNEGOC,CODPARC,CODTIPOPER,DHTIPOPER,TIPMOV,DTALTER,CODUSUINC)
		    	VALUES (V_NUNOTA,1,SYSDATE,V_CODEMP,V_CODPARC,701,(SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = 701),'T',SYSDATE,V_USUINC);

		    FOR I IN 1..V_NROITENS --VERIFICA CADA PRODUTO DA NOTA
		    LOOP
		        SELECT CODPROD INTO V_CODPROD FROM TGFITE WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
		   		SELECT CONTROLE INTO V_CONTROLE FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   		SELECT CODLOCALORIG INTO V_LOCAL FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		    	SELECT (ESTOQUE - RESERVADO) INTO V_QTDDISPONIVEL FROM TGFEST WHERE CODPROD = V_CODPROD AND CONTROLE = V_CONTROLE AND CODLOCAL = V_LOCAL;
			    SELECT QTDNEG INTO V_QTDNEG FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   	    SELECT CODVOL INTO V_CODVOL FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
				SELECT USOPROD INTO V_USOPROD FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
				V_SEQ := V_SEQ + 1;
		
		        IF V_QTDNEG > V_QTDDISPONIVEL THEN --PARA CADA PRODUTO DA NOTA COM ESTOQUE INSUFICIENTE SERÁ ADICIONADO O PRODUTO NA NOTA DE TRANSFERENCIA
                    IF V_QTDDISPONIVEL < 0 THEN
                        V_QTDTRANSF := V_QTDDISPONIVEL * -1;
                    ELSE
                    	V_QTDTRANSF := V_QTDDISPONIVEL;
                    END IF;

		            INSERT INTO TGFITE (NUNOTA,CODPROD,CONTROLE,CODLOCALORIG,CODVOL,QTDNEG,SEQUENCIA,CODEMP,USOPROD,DTALTER)
		            	VALUES (V_NUNOTA,V_CODPROD,V_CONTROLE,V_LOCAL,V_CODVOL,V_QTDTRANSF,V_SEQ,1,V_USOPROD,SYSDATE);
		        END IF;
		       
		    END LOOP;
		END IF;
	END; 
	
END;	
END AD_LANCA_TRANFERENCIA;