CREATE OR REPLACE PROCEDURE         AD_LANCA_COTACAO (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS 
BEGIN
	
DECLARE

	V_CODPROD NUMBER;
	V_SOLCOMPRA VARCHAR2(1);
	V_NROCOT NUMBER;
	V_CODNAT NUMBER;
	V_CODCENCUS NUMBER;
	V_QTDDISPONIVEL NUMBER;
	V_QTDNEG NUMBER;
	V_QTDCOTADA NUMBER;
	V_NROITENS NUMBER;
	V_COTAR INT := 0;
	V_CONTROLE VARCHAR2(50);
	V_LOCAL NUMBER;
	V_CODPARCFORN NUMBER;
	V_CODVOL VARCHAR(5);
	V_TEMEST VARCHAR2(1);
	V_NUNOTAORIG NUMBER;

BEGIN
	
	P_SUCESSO := 'S';
	SELECT NVL(MAX(NUMCOTACAO),0)+1 INTO V_NROCOT FROM TGFCOT;
	SELECT NVL(CODNAT,0) INTO V_CODNAT FROM TGFCAB WHERE NUNOTA = P_NUNOTA; 
	SELECT NVL(CODCENCUS,0) INTO V_CODCENCUS FROM TGFCAB WHERE NUNOTA = P_NUNOTA;
	SELECT COUNT(CODPROD) INTO V_NROITENS FROM TGFITE WHERE NUNOTA = P_NUNOTA;


	BEGIN
		FOR I IN 1..V_NROITENS --VERIFICA SE O PRODUTO TEM ESTOQUE DISPONÍVEL SUFICIENTE
		LOOP
		    SELECT CODPROD INTO V_CODPROD FROM TGFITE WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
		   	SELECT CONTROLE INTO V_CONTROLE FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   	SELECT CODLOCALORIG INTO V_LOCAL FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		    SELECT QTDNEG INTO V_QTDNEG FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   	SELECT (CASE WHEN COUNT(CODPROD) > 0 THEN 'S' ELSE 'N' END) INTO V_TEMEST FROM TGFEST WHERE CODPROD = V_CODPROD; --VERIFICA SE O PRODUTO TEM LINHA NA TGFEST
			
		   	IF V_TEMEST = 'S' THEN --SE HOUVER LINHA NA TGFEST VERIFICA A O ESTOQUE DISPONÍVEL
		   		SELECT (ESTOQUE - RESERVADO) INTO V_QTDDISPONIVEL FROM TGFEST WHERE CODPROD = V_CODPROD AND CONTROLE = V_CONTROLE AND CODLOCAL = V_LOCAL;
		   	ELSE -- SE NÃO HOUVER INSERE UM REGISTRO E FAZ PEGA O DISPONÍVEL
		   		INSERT INTO TGFEST
					(CODEMP, CODLOCAL, CODPROD, CONTROLE, RESERVADO, ESTMIN, ESTMAX, ATIVO, CODBARRA, DTVAL, TIPO, CODPARC, PERCPUREZA, PERCGERMIN, ESTOQUE, DTFABRICACAO, STATUSLOTE, MD5PAF, DTENTRADA, QTDPEDPENDEST, WMSBLOQUEADO, PERCVC, CODAGREGACAO)
					VALUES(3, V_LOCAL, V_CODPROD, V_CONTROLE, V_QTDNEG, 0, 0, 'S', NULL, NULL, 'P', 0, NULL, NULL, 0, NULL, 'N', NULL, NULL, NULL, NULL, NULL, NULL);
				SELECT (ESTOQUE - RESERVADO) INTO V_QTDDISPONIVEL FROM TGFEST WHERE CODPROD = V_CODPROD AND CONTROLE = V_CONTROLE AND CODLOCAL = V_LOCAL;
			END IF;
		   
		    IF V_QTDNEG > V_QTDDISPONIVEL THEN
		        V_COTAR := V_COTAR + 1; --SOMA 1 NA CONTAGEM PARA CADA PRODUTO COM ESTOQUE INSUFICIENTE
		    END IF;
		END LOOP;

		IF V_COTAR > 0 THEN --SE HOUVER AO MENOS 1 PRODUTO COM ESTOQUE INSUFICIENTE SERÁ LANÇADO UMA COTAÇÃO
		    INSERT INTO TGFCOT (NUMCOTACAO,DHINIC,SITUACAO,CODUSUREQ,CODUSURESP,GERPEDREAL,CODNAT,CODCENCUS,NUNOTAORIG,NUMNOTAORIG,CODEMP,PESOPRECO,DTALTER)
		    SELECT V_NROCOT,SYSDATE,'A',C.CODUSUINC,0,'S',V_CODNAT,V_CODCENCUS,C.NUNOTA,C.NUMNOTA,C.CODEMP,1,SYSDATE
		    FROM TGFCAB C WHERE C.NUNOTA = P_NUNOTA;

		    FOR I IN 1..V_NROITENS --VERIFICA CADA PRODUTO DA NOTA
		    LOOP
		        SELECT CODPROD INTO V_CODPROD FROM TGFITE WHERE NUNOTA = P_NUNOTA AND SEQUENCIA = I;
		   		SELECT CONTROLE INTO V_CONTROLE FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		   		SELECT CODLOCALORIG INTO V_LOCAL FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		    	SELECT (ESTOQUE - RESERVADO) INTO V_QTDDISPONIVEL FROM TGFEST WHERE CODPROD = V_CODPROD AND CONTROLE = V_CONTROLE AND CODLOCAL = V_LOCAL;
			    SELECT QTDNEG INTO V_QTDNEG FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		        SELECT SOLCOMPRA INTO V_SOLCOMPRA FROM TGFPRO WHERE CODPROD = V_CODPROD;
		       	SELECT CODPARCFORN INTO V_CODPARCFORN FROM TGFPRO WHERE CODPROD = V_CODPROD;
		   	    SELECT CODVOL INTO V_CODVOL FROM TGFITE WHERE NUNOTA = P_NUNOTA AND CODPROD = V_CODPROD;
		
		        IF V_QTDNEG > V_QTDDISPONIVEL AND V_SOLCOMPRA = 'S' THEN --PARA CADA PRODUTO DA NOTA COM ESTOQUE INSUFICIENTE E QUE ESTEJA MARCADO PARA GERAR SOLICITAÇÃO DE COMPRA NO CADASTRO DE PRODUTO SERÁ ADICIONADO O PRODUTO NA COTAÇÃO
                    IF V_QTDDISPONIVEL < 0 THEN
                        V_QTDCOTADA := V_QTDDISPONIVEL * -1;
                    ELSE
                    	V_QTDCOTADA := V_QTDDISPONIVEL;
                    END IF;
		
		            INSERT INTO TGFITC (NUMCOTACAO,CODPROD,CODPARC,CONTROLE,CODLOCAL,CODVOL,QTDCOTADA,SITUACAO,CABECALHO,RESPMINCOT,AD_NRONOTAORIG)
		            	VALUES (V_NROCOT,V_CODPROD,0,V_CONTROLE,V_LOCAL,V_CODVOL,V_QTDCOTADA,'P','S',1,P_NUNOTA);
		        END IF;
		    END LOOP;
		   
		  	UPDATE TGFCAB SET AD_OBSCOTACAO = 'GERADO A SOLICITAÇÃO DE COMPRA NRO: '|| V_NROCOT WHERE NUNOTA = P_NUNOTA;
		  	UPDATE TGFCAB SET AD_STATUSPEDIDO = 'PPRO' WHERE NUNOTA = P_NUNOTA;
		   
		END IF;
	END; 
	
END;	
END AD_LANCA_COTACAO;