CREATE OR REPLACE PROCEDURE TESTE."AD_UNIFICA_FIN" (
       P_CODUSU NUMBER,        -- Código do usuário logado
       P_IDSESSAO VARCHAR2,    -- Identificador da execução. Serve para buscar informações dos parâmetros/campos da execução.
       P_QTDLINHAS NUMBER,     -- Informa a quantidade de registros selecionados no momento da execução.
       P_MENSAGEM OUT VARCHAR2 -- Caso seja passada uma mensagem aqui, ela será exibida como uma informação ao usuário.
) AS
    FIELD_NUNOTA NUMBER;
    
    V_NUFIN NUMBER;
    V_CODEMP NUMBER;
    V_DTNEG DATE;
    V_DTVENC DATE;
    V_CODPARC NUMBER;
    V_CODTIPTIT NUMBER;
    V_OPERACAO NUMBER;
    V_NUMNOTA NUMBER;	
    V_VLRDESDOB NUMBER;	
    V_CODNAT NUMBER;
    V_HISTORICO VARCHAR2(100);
    V_CONTABANCO NUMBER;
    V_STATUSNOTA VARCHAR2(1);
    V_NFS VARCHAR(1);
    V_LINHAS NUMBER;
    V_NUFINNOVO NUMBER;
    V_AGRUPADO NUMBER;
      
BEGIN
	  
	SELECT MAX(NUFIN)+1 INTO V_NUFINNOVO FROM TGFFIN;
	  
	FOR I IN 1..P_QTDLINHAS -- Este loop permite obter o valor de campos dos registros envolvidos na execução.
	LOOP                    -- A variável "I" representa o registro corrente.

		FIELD_NUNOTA := ACT_INT_FIELD(P_IDSESSAO, I, 'NUNOTA');
		SELECT CODPARC INTO V_CODPARC FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT NUFIN INTO V_NUFIN FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT CODEMP INTO V_CODEMP FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT DTNEG INTO V_DTNEG FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT DTVENC INTO V_DTVENC FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT NUMNOTA INTO V_NUMNOTA FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT VLRDESDOB INTO V_VLRDESDOB FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT NVL(CODNAT,0) INTO V_CODNAT FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT HISTORICO INTO V_HISTORICO FROM TGFFIN WHERE NUNOTA  = FIELD_NUNOTA;
		SELECT CODCTABCOINT INTO V_CONTABANCO FROM TGFFIN WHERE NUNOTA = FIELD_NUNOTA;
		SELECT CODTIPOPER INTO V_OPERACAO FROM TGFCAB WHERE NUNOTA = FIELD_NUNOTA;
		SELECT (CASE WHEN NFSE = 'N' THEN 'S' ELSE 'N' END) INTO V_NFS FROM TGFTOP WHERE CODTIPOPER = V_OPERACAO AND DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = V_OPERACAO);
		SELECT NVL(AD_FINAGRUPADO,0) INTO V_AGRUPADO FROM TGFCAB WHERE NUNOTA = FIELD_NUNOTA;
           
        IF V_NFS = 'S' THEN
			SELECT (CASE WHEN STATUSNOTA = 'L' AND STATUSNFSE = 'A' THEN 'S' ELSE 'N' END) INTO V_STATUSNOTA FROM TGFCAB WHERE NUNOTA = FIELD_NUNOTA;
		ELSIF V_NFS = 'N' THEN
			SELECT (CASE WHEN STATUSNOTA = 'L' AND STATUSNFE = 'A' THEN 'S' ELSE 'N' END) INTO V_STATUSNOTA FROM TGFCAB WHERE NUNOTA = FIELD_NUNOTA;
		END IF;
			
		IF V_STATUSNOTA = 'S' THEN 
			IF V_AGRUPADO = 0 THEN
				INSERT INTO AD_TGFFINAN (NUFIN,CODEMP,NUMNOTA,NUNOTA,NFSE,DTNEG,DHMOV,DTVENCINIC,DTVENC,CODPARC,CODCTABCOINT,CODNAT,CODTIPTIT,HISTORICO,VLRDESDOB,DTALTER)
				VALUES (V_NUFIN,V_CODEMP,V_NUMNOTA,FIELD_NUNOTA,V_NFS,V_DTNEG,V_DTNEG,V_DTVENC,V_DTVENC,V_CODPARC,V_CONTABANCO,V_CODNAT,4,V_HISTORICO,V_VLRDESDOB,TO_CHAR(SYSDATE, 'DD/MM/YYYY'));
			ELSE
				P_MENSAGEM := 'FINANCEIRO DA NOTA ' || FIELD_NUNOTA || ' JÁ AGRUPADO NO NUFIN NRO ' || V_AGRUPADO || '!';
				DELETE FROM AD_TGFFINAN;
			END IF;
		ELSE
			P_MENSAGEM := 'NOTA ' || FIELD_NUNOTA || ' NÃO APROVADA';
			DELETE FROM AD_TGFFINAN;
		END IF;
		
	END LOOP;

	SELECT COUNT(*) INTO V_LINHAS FROM AD_TGFFINAN;
      
	IF V_LINHAS > 0 THEN
		INSERT INTO TGFFIN 
			(NUFIN,ORIGEM,CODEMP,NUMNOTA,NUNOTA,DTNEG,DHMOV,DTVENCINIC,DTVENC,CODPARC,CODTIPOPER,DHTIPOPER,CODCTABCOINT,CODNAT,CODTIPTIT,HISTORICO,VLRDESDOB,RECDESP,DTALTER)
		SELECT 
			V_NUFINNOVO,
			'E',
			CODEMP,
			NUMNOTA,
			NUNOTA,
			DTNEG,
			DHMOV,
			DTVENCINIC,
			DTVENC,
			CODPARC,
			1300,
			(SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = 1300),
			CODCTABCOINT,
			CODNAT,
			4,
			('NOTAS RELACIONADAS: ' || (SELECT LISTAGG(NUMNOTA, ',') WITHIN GROUP (ORDER BY NUFIN) FROM AD_TGFFINAN)),
			(SELECT SUM(VLRDESDOB) FROM AD_TGFFINAN),
			1,
			DTALTER
		FROM AD_TGFFINAN WHERE NFSE = 'S';
   
	DELETE FROM TGFFIN WHERE NUFIN IN (SELECT NUFIN FROM AD_TGFFINAN);
   
	UPDATE TGFCAB SET AD_FINAGRUPADO = V_NUFINNOVO WHERE NUNOTA IN (SELECT NUNOTA FROM AD_TGFFINAN);
   /*UPDATE TGFFIN 
		SET NUNOTA = (SELECT NUNOTA FROM AD_TGFFINAN WHERE NFSE = 'S'), NUMNOTA = (SELECT NUMNOTA FROM AD_TGFFINAN WHERE NFSE = 'S') WHERE NUFIN = V_NUFINNOVO;*/
	--DELETE FROM AD_TGFFINAN;
  
	P_MENSAGEM := 'FINANCEIRO GERADO COM SUCESSO. NRO NUFIN: ' || V_NUFINNOVO || '!';

END IF;

END;